### PR TITLE
Schematics

### LINKED ISSUE #76: Create angular schematics for shallow-render
I'd like to propose to add Angular schematics, so when you create a component with Angular CLI, instead of a default spec file, a shallow-render spec file is generated.

Let's say you execute: `ng g c app/shallow-component`
It would generate the following spec file:
```typescript
import { ShallowComponentComponent } from './shallow-component.component';
import { AppModule } from './app.module';
import { Shallow } from 'shallow-render/dist';

describe('ShallowComponentComponent', () => {
  let shallow: Shallow<ShallowComponentComponent>;

  beforeEach(() => {
    shallow = new Shallow(ShallowComponentComponent, AppModule);
  });

  it('should create', async () => {
    const { instance } = await shallow.render();
    expect(instance).toBeTruthy();
  });
});
```

@getsaf If you are interested, I can help with a PR as I have got a working solution already.

### PR DESCRIPTION
**Pull request by mihalcan**
resolves #76

- replaces default TestBed component spec file with shallow-render during execution of `ng generate component`

- `ng add shallow-render` - adds shallow-render dependency, installs it and sets default collection to shallow-render

### CODE REVIEW

**Comment by getsaf** [comment]
Thanks for the PR, you've done a lot of work! I didn't realize that schematics needed their own build process. I have some concerns with mixing in the schematics build dependencies with the core shallow-render dependencies.

Just one example is that I can't upgrade Typescript past v2.7 or I risk breaking compatibility with Angular 5x. 

How do you feel about isolating the schematics code/build under the `/schematics` folder with its own `package.json` so we don't have any conflicts? This way it's clear which dependencies go with which build processes. Since we're using `node` module resolution, you could even apply only the *additional* packages the schematics build needs from the root `package.json`.

Thoughts?

**Comment by mihalcan** [comment]
To be honest the first version had its own package.json 😄. 

If we can't update typescript version then I'll move schematics into a separate folder, as I don't see other ways of overcoming this problem

**Comment by getsaf** [comment]
Aww man, at least you've already got most of the separation done since it's mostly already locked away in that folder.

Once you have it separated, I'll pull it down and test it with the build to make sure it gets built/distributed properly during the publish process, and run through a few NG5 compatiblity tests to make sure it supports all the versions shallow currently supports.

**Comment by mihalcan** [comment]
I'd like to clarify a few points:

1. Would you like schematics to be a separate package completely (I mean separate build, versioning, packaging, etc) but it just lives under the same repo?
2. Probably can be answered by the first point, when building shallow-render, would you want to rebuild schematics as well?

It would be great if we could discuss the implementation details in a slack channel or similar

**Comment by getsaf** [comment]
Considering the build process for schematics, those are good questions.
I've got a little time this morning if you're around:

https://join.slack.com/t/domainexperts/shared_invite/enQtNTE0MTI0NDkwNzkxLTA4MmM3MjAzOTM0ZjVkNTkyOTU4ODExNTk5MjAzZDM0YmJkZGEzZDk0ZTZiYzlhNmQxZWY5ODVmYzYzZjU1ZGQ

**Comment by getsaf** [comment]
See comments in #80

**Pull request closed without merging**
